[package]
name = "mew-transaction"
version.workspace = true
edition.workspace = true

[dependencies]
mew-core.workspace = true
mew-graph.workspace = true
mew-registry.workspace = true
mew-constraint.workspace = true
mew-rule.workspace = true
mew-mutation.workspace = true
thiserror.workspace = true
