[package]
name = "mew-compiler"
version.workspace = true
edition.workspace = true

[dependencies]
mew-core.workspace = true
mew-graph.workspace = true
mew-parser.workspace = true
mew-registry.workspace = true
thiserror.workspace = true
