[package]
name = "mew-query"
version.workspace = true
edition.workspace = true

[dependencies]
mew-core.workspace = true
mew-graph.workspace = true
mew-pattern.workspace = true
mew-registry.workspace = true
thiserror.workspace = true
